### ISSUE TITLE
OSM Attribution

### ISSUE THREAD

**Issue by tordans** [placemark/figma-plugin#11]
This might already be solved, but just in case …

> unlimited printing & reproduction | yes

… could have a note reminding people to attribute OSM. Which IMO is the requirement to reproduction (in this situation).

Ideally, the Plugin would put the `(c) OpenStreetMap` not in output in Figma.

**Comment by tmcw** [comment]
> Ideally, the Plugin would put the (c) OpenStreetMap not in output in Figma.

This is exactly what it does right now.

**Comment by tmcw** [comment]
Closing - what I'm doing currently (embedding the text "OpenStreetMap" in the top-left corner of all generated images, and including the same in the splash image) falls within the current OSMF [safe harbor requirements.](https://wiki.osmfoundation.org/wiki/Licence/Attribution_Guidelines#Requirements_to_fit_within_OSMF%E2%80%99s_safe_harbour)
